services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - keycloak:/opt/keycloak/data
      - ./js-policies/target/js-policies.jar:/opt/keycloak/providers/js-policies.jar
    ports:
      - 9999:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev

volumes:
  keycloak: