services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - keycloak:/opt/keycloak/data
      - ./master-realm.json:/opt/keycloak/realm-export.json
      - ./js-policies/target/js-policies.jar:/opt/keycloak/providers/js-policies.jar
      - ./action-token-example.jar:/opt/keycloak/providers/action-token-example.jar
    ports:
      - 9900:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
    entrypoint: sh
    command:
      - -c
      - /opt/keycloak/bin/kc.sh import --file /opt/keycloak/realm-export.json && /opt/keycloak/bin/kc.sh start-dev
volumes:
  keycloak: